config/routes.rb
Rails.application.routes.draw do
  

  root 'user_sessions#new'

  resources :users, shallow: true, only: [:new, :create] do

    resources :groups, shallow: true do

      resources :subgroups, shallow:true do
        resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

      end

      resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

    end

  end

  resource :user_session, only: [ :new, :create, :destroy ]

end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :name, presence: true, :on=>[:update, :create]
	validates :name, uniqueness: { scope: :user_id,
    message: "Group exists!" }, :on=>[:update, :create]
  	belongs_to :user
  	has_many :subgroups, dependent: :destroy
  	has_many :clients, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 before_action :require_user
	
	def index

		@groups=current_user.groups
		@group = current_user.groups.build
    @grouped=Group.find_by_id(params[:id])
    @subgroup=Subgroup.new
    @client=Client.new

    #all clients for current user
    @clients= Array.new
    #search
   

      @groups.each do |group|

      group.clients.where("name LIKE ? OR surname LIKE? OR company LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%").each do |client|
       @clients.push(client)
      end

     group.subgroups.each do |subgroup|
       subgroup.clients.where("name LIKE ? OR surname LIKE? OR company LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%").each do |client|
       @clients.push(client)
      end
    end

    end
  

    #current_user.groups.delete_all
  end

    def show
    @group = Group.find(params[:id])
    @clients= Array.new

    @group.clients.each do |client|
    @clients.push(client)
    end

     @group.subgroups.each do |subgroup|
       subgroup.clients.each do |client|
       @clients.push(client)
      end
    end
    respond_to do |format|
        format.js {}
    end
  end

 
	def create
    @group = current_user.groups.build(group_params)
   if @group.save
    @subgroup=Subgroup.new
    @client=Client.new
    respond_to do |format|

      format.html do
        redirect_to user_groups_path(current_user),
          notice: "Group is added!"
      end

      format.js do
        render
      end

    end
  else
    render :js => "alert('Group exists or you do not enter a value');"
  end

  end

  def update
     @group=Group.find_by_id(params[:id])
    if @group.update(group_params)
      respond_to do |format|
        format.html do
          redirect_to user_groups_path(current_user),
          notice: "Group is updated!"
        end

        format.js do
         render
        end

      end
    else 
    render :js => "alert('Group exists or you do not enter a value');"
    end

  end


 def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to user_groups_path(current_user),
      notice: "Group is deleted!"
  end

	private
	def group_params
    params.require(:group).permit(:name)
  end

  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_clients.html.erb
<p id="titleClientsInfo" class="titleMain">Clients information</p>

<%if clients.count==0 %>
<p class="titleTableInfo">No one client</p>
<%else %>
<table style="margin: 15px;">
<tr>
	<th class="titleTableInfo">No.</th>
	<th class="titleTableInfo">Name</th>
	<th class="titleTableInfo">Surname</th>
	<th class="titleTableInfo">Phone</th>
	<th class="titleTableInfo">Email</th>
	<th class="titleTableInfo">Company</th>
	<th class="titleTableInfo">Job position</th>
	<th class="titleTableInfo">Address</th>
	<th class="titleTableInfo">City</th>
	<th class="titleTableInfo">Country</th>
</tr>
<%i=1%>
<%clients.each do |client| %>
<tr>
	<td class="bodyTableInfo"><%=i%>.</td>
	<td class="bodyTableInfo"> <%=client.name%> </td>
	<td class="bodyTableInfo"><%=client.surname%> </td>
	<td class="bodyTableInfo"><%=client.phone%> </th>
	<td class="bodyTableInfo"><%=client.email%> </td>
	<td class="bodyTableInfo"><%=client.company%> </td>
	<td class="bodyTableInfo"><%=client.job_position%> </td>
	<td class="bodyTableInfo"><%=client.address%> </td>
	<td class="bodyTableInfo"><%=client.city%> </td>
	<td class="bodyTableInfo"><%=client.country%> </td>
	<td class="bodyTableInfo"><%=link_to "See notes", client, remote:true%>
	<td class="bodyTableInfo"><%=link_to "Edit", edit_client_path(client)%>
	<td class="bodyTableInfo" ><%=link_to "Delete", client_path(client), method: :delete, 
	'data-confirm' => "Are you sure to delete client  '#{client.name}' '#{client.surname}'?" %>
</tr>
<%i=i+1%>
<%end%>

</table>
<%end%>

app/views/groups/_group.html.erb
 
    <tr>
      <td>

        <table>

          <tr style="border-bottom-color: rgb(255,0,0); 
                     border-bottom-style: solid;
                      border-bottom-width: 2px;
                       margin-top: 10px;
                       margin-bottom:5px;">
            <td>
              <a href="#" id="parent<%=group.id%>" onclick="hideChild(this.id);">
                <img src="/assets/collapse.jpg" id="img<%=group.id%>"/>
              </a>
        <%= link_to group.name, group, id: "link#{group.id}", class: "listGroup", remote:true %> 
      </td>

      <td>
        <%= link_to "Edit",  "#", onclick: "show_form_edit_group(#{group.id});", class: 'visibleButton', id: "edit#{group.id}" %>
      </td>

      <td>
        <%= button_to "Delete", group_path(group),
        method: :delete, id: "delete#{group.id}",
        class: 'visibleButton',
        'data-confirm' => "Are you sure to delete this group?" %> 
      </td>
    </tr>
  
    <tr>
      <%=form_for group, remote:true do |f| %>
        <td>
          <%=f.text_field :name, id: group.id, value: group.name, disabled: "disabled", style: "display:none;"%>
        </td>
        <td>
         <%= f.submit class: 'updateButton', :id=>"submit#{group.id}"%>
        </td>
     <% end %>
   </tr>
</table>
</td>
</tr>
   <tr><td>
   
      <!-- List subgroups-->
  
  <table id="subgroup<%=group.id%>" class="groups_child">

   <tr>
    <td>
      <a href="#" id="parentSubgroup<%=group.id%>" onclick="hideChild(this.id);" class="listSubgroupParent">
      <img src="/assets/collapse.jpg" id="imgSubgroup<%=group.id%>"/>
      Subgroups</a>
    </td>
  </tr>

  <tr><td><table id="subgroup1_<%=group.id%>" class="groups_child">
   
  <%group.subgroups.each do |subgroup| %>
  
   <%=render subgroup %>
 
  <% end %>

  </table></td></tr>


<tr><td>
  <a href="#" id="parentClient<%=group.id%>" onclick="hideChild(this.id);" class="listSubgroupParent">
      <img src="/assets/collapse.jpg" id="imgClient<%=group.id%>"/>
      Clients</a>
    </td>
  </tr>
  <tr><td>
  <!--child clients-->
  <table id="clients<%=group.id%>" class='groups_child'>
   
   
  <%group.clients.each do |client| %>
    <tr>
      <td>
        <%= link_to "#{client.name} #{client.surname} - #{client.company}", client, id: "linkClient#{client.id}", class: "listSubgroup", remote:true %> 
      </td> 
    </tr>
  <% end %>

  </table>
</td></tr>
</table></td></tr>

<tr><td>

    <!--form for create a new subgroup -->
  <table  id="new_subgroup_table">
    <tr style="border-bottom-color: rgb(255,255,255); 
                     border-bottom-style: solid;
                      border-bottom-width: 2px;
                       margin-top: 10px;
                       margin-bottom:10px;
                       text-align:right;">
      <td>
        <%= link_to "New subgroup", "#", onclick: "show_form_group('#{group.id}');", class: 'newButtonSubgroup' %>
        <!--Add new group -->
        <div id="form_new_subgroup<%=group.id%>" style='display:none'>

           <%=form_for [group, @subgroup],  remote: true do |f|%>

           <div >
             <%= f.label :name, class: "newGroupFormSubgroup" %>
             <%= f.text_field :name, id: "new_subgroup_value#{group.id}", class: "newGroupFormSubgroup" %>
            </div>

           <div>
             <%= f.submit class: 'newButtonSubgroup' %>
            </div>

          <% end %>

          </div>
      </td>
    </tr>
  </table>
</td></tr>
  <!-- form for create new client direct for group -->
<tr><td>
  <table  id="new_group_client_table">
    <tr style="border-bottom-color: rgb(255,255,255); 
                     border-bottom-style: solid;
                      border-bottom-width: 2px;
                       margin-top: 10px;
                       margin-bottom:10px;
                       text-align:right;">
      <td>
        <%= link_to "New client in group", new_group_client_path(group), class: "linkNewClient"%>
        
      </td>
    </tr>
  </table>

    
  </td>
</tr>
 

app/views/groups/create.js.erb
$('#show_list').append("<%= escape_javascript(render @group) %>");
$('#form_new_group').css('display','none');
$('#new_group_value').val('');

app/views/groups/index.html.erb
<div id="headerLog" class="divHeaderLog">
  <ul id="ulHeaderLog" class='headerLog'>
    <li>
<p class='titlePage'>Simple CRM<p> 
</li>

<li>
  <p>
  <%= form_tag user_groups_path(current_user), method: :get, role: 'search' do %>
        <%= search_field_tag :q, params[:q], placeholder: "Search by name or surname or company", class: 'search' %>
        <%= submit_tag "Search", class: 'searchButton' %>
      <% end %>
    </p>
</li>

<li>
  <p class="userName">
<%=current_user.username%>
</p>
</li>
<li>
  <p>
  <%= link_to "Log out", user_session_path, method: :delete, class: 'logout'%>
</p>
 </li>

 </ul>
</div>



<div id="tree_menu" class="tree_menu">
<p class="titleList">List of client groups</p>
<!--show all groups -->

<table id="show_list">
  
  <% @groups.each do |group| %>
   <%=render group %>
  
  <% end %>
  </table>

<!--form for create a new group -->
  <table  id="new_group_table">
    <tr>
      <td>
        <%= link_to "New group", "#", onclick: "show_form_group('group');", class: 'newButton' %>
        <!--Add new group -->
        <div id="form_new_group" style='display:none'>

           <%=form_for [current_user, @group],  remote: true do |f|%>

           <div >
             <%= f.label :name, class: "newGroupForm" %>
             <%= f.text_field :name, id: "new_group_value", class: "newGroupForm" %>
            </div>

           <div>
             <%= f.submit  class: 'newButton' %>
            </div>

          <% end %>

          </div>
      </td>
    </tr>
  </table>


</div>


<div id="main_log" class="main_log">
  <%=render 'clients', :clients=>@clients%>
</div>

app/views/groups/show.js.erb
$("#main_log").html("<%= escape_javascript(render 'clients', :clients=>@clients)%>");
$("#titleClientsInfo").after("<p class='titleTableInfo'> Clients in group <%=@group.name%></p>");

app/views/groups/update.js.erb
var visibleButton={"display":"block",
	"color": "rgb(44,105,157)",
	"background-color": "rgb(255,255,255)",
	"width": "60px",
	"text-align": "center",
	"font-size": "0.8em",
	"margin-left":"10px",
	"margin-top": "5px",
	"font-weight": "bold"};

$('#submit<%= @group.id %>').css('display','none');
$('#<%= @group.id %>').css('display','none');
$('#link<%= @group.id %>').show();
$('#edit<%= @group.id %>').css(visibleButton);
$('#delete<%= @group.id %>').css(visibleButton);
$('#<%=@group.id %>').prop('disabled',true);
$('#link<%= @group.id %>').html('<%=@group.name%>');