config/routes.rb
Rails.application.routes.draw do
  

  root 'user_sessions#new'

  resources :users, shallow: true, only: [:new, :create] do

    resources :groups, shallow: true do

      resources :subgroups, shallow:true do
        resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

      end

      resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

    end

  end

  resource :user_session, only: [ :new, :create, :destroy ]

end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :name, :surname, :city, :phone, presence: true
	belongs_to :group
	has_many :notes, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
before_action :require_user
def new
@group=Group.find_by_id(params[:group_id])
@client=@group.clients.build if @group

@subgroup=Subgroup.find_by_id(params[:subgroup_id])
@client=@subgroup.clients.build if @subgroup
end 

def create
@group=Group.find_by_id(params[:group_id])
@client=@group.clients.build(clients_params) if @group

@subgroup=Subgroup.find_by_id(params[:subgroup_id])
@client=@subgroup.clients.build(clients_params) if @subgroup


   if @client.save
        redirect_to user_groups_path(current_user),
          notice: "Client is added!"
    
  else
    render 'new'
  end

end

def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(clients_params)
      redirect_to user_groups_path(current_user),
        notice: "Clients information is updated!"
    else
      render 'edit'
    end
  end

 def show
    @client = Client.find(params[:id])
    @note=Note.new
    @notes=@client.notes
    respond_to do |format|
        format.js {}
    end
  end


def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to user_groups_path(current_user),
      notice: "Client is deleted!"
  end


private
	def clients_params
    params.require(:client).permit(:name, :surname, :address, :city, :country, :phone, :fax, :job_position, :email, :company)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<%= form_for [@group || @subgroup, @client] do |f| %>
  <% if @client.errors.any? %>
    <h3><%= t('validation_errors', count: @client.errors.count) %></h3>

    <ul>
      <% @client.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <table>
    <tr>
      <td class='tableNewClient'><%= f.label :name %>*</td>
      <td class='tableNewClient'><%= f.text_field :name %></td>
  </tr>

  <tr>
    <td class='tableNewClient'><%= f.label :surname %>*</td>
    <td class='tableNewClient'><%= f.text_field :surname %></td>
  </tr>

  <tr>
    <td class='tableNewClient'><%= f.label :address %></td>
    <td class='tableNewClient'><%= f.text_field :address %></td>
  </tr>

   <tr>
    <td class='tableNewClient'><%= f.label :city %>*</td>
    <td class='tableNewClient'><%= f.text_field :city %></td>
  </tr>
  <tr>
    <td class='tableNewClient'><%= f.label :country %>*</td>
    <td>
      <%require 'uri' %>
      <%require 'net/http'%>
      <%require 'nokogiri'%>
      <%search_url="http://www.listofcountriesoftheworld.com/" %>
      <%search_uri=URI(search_url)%>
      <%body=Net::HTTP.get(search_uri)%>

      <%doc=Nokogiri::HTML.parse(body)%>
      <%state=doc.xpath('//div[@id="ctry"]/a')%>
      <%=f.select (:country) do %> 
      <%state.each do |i| %>
      <%=content_tag(:option, i.text, value: i.text) %>
      <%end %>
    <%end %>
     
    </td>
  </tr>


  <tr>
    <td class='tableNewClient'><%= f.label :phone %>*</td>
    <td class='tableNewClient'><%= f.text_field :phone %></td>
  </tr>

  <tr>
    <td class='tableNewClient'><%= f.label :fax %></td>
    <td class='tableNewClient'><%= f.text_field :fax %></td>
  </tr>
<tr>

  <tr>
    <td class='tableNewClient'><%= f.label :email %></td>
    <td class='tableNewClient'><%= f.text_field :email %></td>
  </tr>
<tr>
    <td class='tableNewClient'><%= f.label :job_position %></td>
    <td class='tableNewClient'><%= f.text_field :job_position %></td>
  </tr>

  <tr>
    <td class='tableNewClient'><%= f.label :company %></td>
    <td class='tableNewClient'><%= f.text_field :company %></td>
  </tr>
</table>
  
  
    <%= f.submit %>
  
<% end %>

app/views/clients/_clientDetail.html.erb
<p id="titleClientsInfo" class="titleMain">Client information</p>
<table style="margin: 15px;">
<tr>
	<th class="titleTableInfo">Name </th>
	<td class="bodyTableInfo"> <%=client.name%> </td>
</tr>

<tr>
	<th class="titleTableInfo">Surname</th>
	<td class="bodyTableInfo"> <%=client.surname%> </td>
</tr>
<tr>
	<th class="titleTableInfo">Phone</th>
	<td class="bodyTableInfo"> <%=client.phone%> </td>
</tr>
<tr>
	<th class="titleTableInfo">Email</th>
	<td class="bodyTableInfo"> <%=client.email%> </td>
</tr>
<tr>
	<th class="titleTableInfo">Company</th>
	<td class="bodyTableInfo"> <%=client.company%> </td>
	</tr>
<tr>

	<th class="titleTableInfo">Job position</th>
	<td class="bodyTableInfo"> <%=client.job_position%> </td>
	</tr>
<tr>
	<th class="titleTableInfo">Address</th>
	<td class="bodyTableInfo"> <%=client.address%> </td>
	</tr>
<tr>
	<th class="titleTableInfo">City</th>
	<td class="bodyTableInfo"> <%=client.city%> </td>
	</tr>
<tr>
	<th class="titleTableInfo">Country</th>
	<td class="bodyTableInfo"> <%=client.country%> </td>
</tr>

</table>

<%=link_to "Edit", edit_client_path(client), class: 'buttonClientInfo'%>
<%=link_to "Delete", client_path(client), method: :delete, 'data-confirm' => "Are you sure to delete client  '#{client.name}' '#{client.surname}'?", class: 'buttonClientInfo' %>

<p id="titleClientsNotes" class="titleClientsNotes">Notes</p>
<table id="listNotes" style="margin-left: 30px;">

	<%=render 'notesAll', :notes=>client.notes%>
	
</table>

<%=link_to "Add note", "#", onclick: "show_form_notes();", class: 'newButtonNotes' , id: "link_new_note"%>


        <div id="new_note" style='display:none'>
        	<p class="titleClientsNotes">New note</p>
           <%=form_for [client, @note],  remote: true do |f|%>

           <div >
             <%= f.label :title, class: "newNoteForm" %>
             <%= f.text_field :title, id: "new_title_value", class: "newNoteForm" %>
            </div>

            <div >
             <%= f.label :body, class: "newNoteForm" %>
             <%= f.text_area :body, id: "new_body_value", class: "newNoteForm" %>
            </div>

           <div>
             <%= f.submit  class: 'newButtonNote' %>
            </div>

          <% end %>

          </div>
      

app/views/clients/_note.html.erb
<tr id="<%=note.id%>">
	<td class="bodyNotes">
		<%=note.title%>
	</td>
	<td class="bodyNotes">
		<%=note.body%>
	</td>
	<td class="bodyNotes">
		<%=note.created_at%>
	</td>
	<td class="bodyNotes">
		<%=link_to "Delete", note_path(note) , method: :delete, 'data-confirm' => "Are you sure to delete note '#{note.title}'?", remote:true, class: "deleteNotes" %>
	</td>
</tr>

app/views/clients/_notesAll.html.erb
<tr>
	<td class="titleNotes">Title</td>
	<td class="titleNotes">Description</td>
	<td class="titleNotes">Created at</td>
	</tr>

<%notes.each do |note| %>
<%=render 'note', :note=>note%>
<%end%>

app/views/clients/edit.html.erb
<div class="clientForm">
	
	<div class="headerClientForm">
		<p>Update client's information</p>
	</div>

	<div class="bodyClientForm">
		<%=render 'client' %>
	</div>

</div>

app/views/clients/new.html.erb
<div class="clientForm">
	
	<div class="headerClientForm">
		<p>New client - enter following information</p>
	</div>

	<div class="bodyClientForm">
		<%=render 'client' %>
	</div>

</div>

app/views/clients/show.js.erb
$("#main_log").html("<%= escape_javascript(render 'clientDetail', :client=>@client)%>");