config/routes.rb
Rails.application.routes.draw do
  

  root 'user_sessions#new'

  resources :users, shallow: true, only: [:new, :create] do

    resources :groups, shallow: true do

      resources :subgroups, shallow:true do
        resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

      end

      resources :clients, shallow:true do 

        resources :notes, only: [:create,:destroy]

      end

    end

  end

  resource :user_session, only: [ :new, :create, :destroy ]

end

app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: { scope: :group_id,
    message: "Subgroup exists!" }
	belongs_to :group
	has_many :clients, dependent: :destroy
end

app/controllers/subgroups_controller.rb
class SubgroupsController < ApplicationController
	
 before_action :require_user
	def create
    group = Group.find(params[:group_id])
    
    @subgroup = group.subgroups.build(subgroup_params)
     if @subgroup.save
     
      respond_to do |format|
      format.html do
        redirect_to user_groups_path,
          notice: "Subgroup is added!"
      end
      format.js do
        render
      end
    end
  else
  render :js => "alert('Subgroup exists or you do not enter a value');"
end
  end

  def show
    @subgroup = Subgroup.find(params[:id])
    @clients= Array.new

    @subgroup.clients.each do |client|
    @clients.push(client)
    end

    respond_to do |format|
        format.js {}
    end
  end


    def update
     @subgroup=Subgroup.find_by_id(params[:id])
    if @subgroup.update(subgroup_params)
      respond_to do |format|
        format.html do
          redirect_to user_groups_path,
          notice: "Subgroup is updated!"
        end

        format.js do
         render
        end

      end
    else 
      render :js => "alert('Subgroup exists or you do not enter a value');"
    end
  end
  

  def destroy
    @subgroup = Subgroup.find(params[:id])
    @subgroup.destroy
    redirect_to user_groups_path(current_user),
      notice: "Subgroup is deleted!"
  end

private
	def subgroup_params
    params.require(:subgroup).permit(:name)
  end

end

app/helpers/subgroups_helper.rb
module SubgroupsHelper
end

app/views/subgroups/_subgroup.html.erb
<tr>

  <td>
    <a href="#" id ="linkSubgroup<%=subgroup.id%>" class="listSubgroup" onclick= "hideChild(this.id)">
      <img src="/assets/collapse.jpg" id="imgClientSubgroup<%=subgroup.id%>"/></a>
       <%= link_to subgroup.name, subgroup, id: "parentSubgroup#{subgroup.id}", class: "listSubgroup1", remote:true %>
     </td>
  <td>
    <%= link_to "Edit",  "#", onclick: "show_form_edit_group(\"subgroup#{subgroup.id}\" );", class: 'visibleButtonSubgroup', id: "editSubgroup#{subgroup.id}" %>
  </td>

  <td>
    <%= button_to "Delete", subgroup_path(subgroup),
        method: :delete, id: "deleteSubgroup#{subgroup.id}",
        class: 'visibleButtonSubgroup',
        'data-confirm' => "Are you sure to delete this subgroup?" %> 
    </td>

</tr>
  
<tr>

  <%=form_for subgroup, remote:true do |f| %>
    <td>
      <%=f.text_field :name, id: "subgroup#{subgroup.id}", value: subgroup.name, disabled: "disabled", style: "display:none;"%>
    </td>
        
    <td>
      <%= f.submit class: 'updateButtonSubgroup', :id=>"submitSubgroup#{subgroup.id}"%>
    </td>
  <% end %>

</tr>

<tr><td>
  <!--child clients-->
  <table id="clientsSubgroup<%=subgroup.id%>" class='groups_child'>
   
   
  <%subgroup.clients.each do |client| %>
    <tr>
      <td>
        <%= link_to "#{client.name} #{client.surname} - #{client.company}", client, id: "linkClient#{client.id}", class: "listSubgroupClients", remote:true %> 
      </td> 
    </tr>
  <% end %>

  </table>
</td></tr>
  <!-- form for create new client direct for group -->
<tr><td>
  <table  id="new_subgroup_client_table">
    <tr>
      <td>
        <%= link_to "New client in subgroup", new_subgroup_client_path(subgroup), class: "linkNewClientSubgroup"%>
        
      </td>
    </tr>
  </table>

    
  </td>
</tr>



 

app/views/subgroups/create.js.erb
$('#subgroup1_<%=@subgroup.group_id%>').append("<%= escape_javascript(render @subgroup) %>");
$('#form_new_subgroup<%=@subgroup.group_id%>').css('display','none');
$('#new_subgroup_value<%=@subgroup.group_id%>').val('');

app/views/subgroups/show.js.erb
$("#main_log").html("<%= escape_javascript(render 'groups/clients', :clients=>@clients)%>");
$("#titleClientsInfo").after("<p class='titleTableInfo'> Clients in subgroup <%=@subgroup.name%></p>");

app/views/subgroups/update.js.erb
var visibleButton={"display":"block",
	"color": "rgb(44,105,157)",
	"background-color": "rgb(255,255,255)",
	"width": "40px",
	"text-align": "center",
	"font-size": "0.6em",
	"margin-left":"20px",
	"margin-top": "3px",
	"font-weight": "bold"};
	
var text='<img src="/assets/collapse.jpg" id="imgClientSubgroup<%=@subgroup.id%>"/>';
$('#submitSubgroup<%= @subgroup.id %>').css('display','none');
$('#subgroup<%= @subgroup.id %>').css('display','none');
$('#linkSubgroup<%= @subgroup.id %>').show();
$('#parentSubgroup<%= @subgroup.id %>').show();
$('#editSubgroup<%= @subgroup.id %>').css(visibleButton);
$('#deleteSubgroup<%= @subgroup.id %>').css(visibleButton);
$('#subgroup<%=@subgroup.id %>').prop('disabled',true);
$('#linkSubgroup<%= @subgroup.id %>').html(text);
$('#parentSubgroup<%= @subgroup.id %>').text("<%=@subgroup.name%>");